### ISSUE TITLE
./gradlew: Permission denied

### ISSUE THREAD

**Issue by CheezBallzPi** [RoboEagles4828/LandrovalToast#7]
`gradlew` not running anywhere except Windows. Not able to change permissions.

@devoidoflife: Please change the permission in your Mac and push it to master.

**Comment by CheezBallzPi** [comment]
Or anyone with anything that can change permissions.
@RoboEagles4828/senior-programmers

**Comment by vivekmalneedi** [comment]
changed permissions

**Comment by apurvaaggarwal** [comment]
chmod +x gradlew
